# Generated by Django 4.1 on 2023-07-11 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0005_alter_producto_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petstoreapp.boleta')),
            ],
        ),
    ]
