# Generated by Django 4.1 on 2023-07-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petstoreapp', '0006_seguimientoorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='impuesto',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='seguimientoorden',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
